schema_version: 1

context:
  name: pystring
  version: "1.1.5"
  build_number: 1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/imageworks/pystring/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 63c30c251b8017c897bd923826f400aee1d6e4f1c22ffbbd2104f150522a2040
  patches:
    - fix_cmake.patch

build:
  number: ${{ build_number }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.5
    - if: unix
      then:
        - make
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      strict: true
      include:
        - pystring/**
      lib:
        - if: win
          then: pystring.lib
          else: pystring
      bin:
        - if: win
          then: pystring.dll

about:
  homepage: https://github.com/imageworks/pystring
  license: BSD-3-Clause
  license_file: LICENSE
  summary: C++ functions matching the interface and behavior of python string methods with std::string
  repository: https://github.com/imageworks/pystring
  description: |
    Pystring is a collection of C++ functions which match the interface and
    behavior of python's string class methods using std::string. Implemented in
    C++, it does not require or make use of a python interpreter. It provides
    convenience and familiarity for common string operations not included in the
    standard C++ library.

extra:
  recipe-maintainers:
    - carlodri
